AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  auth

Globals:
  Function:
    Timeout: 3

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: function-auth
      Environment:
        Variables:
          JWT_SECRET: !Ref JWTSecretParameter
          RDS_DATABASE: !Ref RDSDatabaseParameter
          RDS_HOSTNAME: !Ref RDSHostnameParameter
          RDS_PASSWORD: !Ref RDSPasswordParameter
          RDS_PORT: !Ref RDSPortParameter
          RDS_USERNAME: !Ref RDSUsernameParameter
      Architectures:
        - x86_64
      Events:
        Auth:
          Type: Api
          Properties:
            Path: /user
            Method: post

Parameters:
  JWTSecretParameter:
    Type: String
    Default: YourDefaultJWTSecretValue

  RDSDatabaseParameter:
    Type: String
    Default: YourDefaultRDSDatabaseValue

  RDSHostnameParameter:
    Type: String
    Default: YourDefaultRDSHostnameValue

  RDSPasswordParameter:
    Type: String
    Default: YourDefaultRDSPasswordValue

  RDSPortParameter:
    Type: Number
    Default: "3306"

  RDSUsernameParameter:
    Type: String
    Default: YourDefaultRDSUsernameValue

Outputs:
  AuthApi:
    Description: "API Gateway endpoint URL for Prod stage for auth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/"
  AuthFunction:
    Description: Auth Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
  AuthFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AuthFunctionRole.Arn
