AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  auth

Globals:
  Function:
    Timeout: 3

Resources:
  FiapAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        FiapAuth:
          Type: Api
          Properties:
            Path: /user
            Method: post

Outputs:
  FiapAuthApi:
    Description: "API Gateway endpoint URL for Prod stage for fiap auth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/"
  FiapAuthFunction:
    Description: Fiap Auth Lambda Function ARN"
    Value: !GetAtt FiapAuthFunction.Arn
  FiapAuthFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FiapAuthFunctionRole.Arn
