name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SAM
        uses: aws-actions/setup-sam@v1

      - name: Build
        run: sam build

      - name: Deploy
        run: sam deploy --profile <profile_name> --region <region> --capabilities CAPABILITY_IAM

      - name: Test
        run: curl -X POST https://<api_gateway_url>
