name: Deploy Lambda using SAM

on:
  push:
    branches:
      - main # ou a branch que você deseja usar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.*'

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-sam-cli

      - name: Package the app
        run: |
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket bucketauthlambda

      - name: Deploy the app
        run: |
          sam deploy --template-file packaged.yaml --stack-name CloudFormationAuthLambda --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
