name: Deploy Lambda using SAM

on:
  push:
    branches:
      - main # ou a branch que você deseja usar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.*'

      - name: Install SAM CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Install Node.js dependencies
        run: npm install

      - name: Configure AWS Credentials
        run: |
          aws configure set region us-east-1

      - name: Package the app
        run: |
          sam package --template-file template.yaml --s3-bucket bucketauthlambda --region us-east-1 --config-env=github --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy the app
        run: |
          sam deploy --template-file packaged.yaml --stack-name CloudFormationAuthLambda --capabilities CAPABILITY_IAM --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
